// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jPoFfni-5risXlb9CHXZJdMtlLoBO3o',
    appId: '1:861402095166:web:b44c99fb13568f9aad3b6f',
    messagingSenderId: '861402095166',
    projectId: 'todolistshmr',
    authDomain: 'todolistshmr.firebaseapp.com',
    storageBucket: 'todolistshmr.appspot.com',
    measurementId: 'G-V92F2DRL1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNO-3IKe2aaV3cGckG8bubQgvmQ3DoVg',
    appId: '1:861402095166:android:183878e64ec4fb99ad3b6f',
    messagingSenderId: '861402095166',
    projectId: 'todolistshmr',
    storageBucket: 'todolistshmr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALRdJgrV7dEeaTZZkNVwQHvyqrZjqRz8s',
    appId: '1:861402095166:ios:56adefe3973e121ead3b6f',
    messagingSenderId: '861402095166',
    projectId: 'todolistshmr',
    storageBucket: 'todolistshmr.appspot.com',
    iosClientId: '861402095166-7dm9t4fr131ep5koaolk0cmcb6ac84h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListShmr',
  );
}
